basePath: /
definitions:
  articles.ArticleBody:
    properties:
      'text:':
        type: string
      title:
        type: string
    type: object
  comments.CommentInput:
    properties:
      text:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Articles:
    properties:
      comments:
        items:
          $ref: '#/definitions/models.Comments'
        type: array
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      isRemoved:
        $ref: '#/definitions/sql.NullBool'
      text:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      userId:
        type: integer
    type: object
  models.Comments:
    properties:
      articleId:
        type: integer
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      isRemoved:
        $ref: '#/definitions/sql.NullBool'
      text:
        type: string
      updatedAt:
        type: string
      userId:
        type: integer
    type: object
  models.HttpResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
  models.LoginInput:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.NewUser:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      id:
        type: integer
      isRemoved:
        $ref: '#/definitions/sql.NullBool'
      password:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  sql.NullBool:
    properties:
      bool:
        type: boolean
      valid:
        description: Valid is true if Bool is not NULL
        type: boolean
    type: object
host: localhost:4000
info:
  contact: {}
  title: Profresource go Application
  version: "1.0"
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: Get all articles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Articles'
            type: array
        "401":
          description: Unauthorized
          schema: {}
      security:
      - Bearer: []
      summary: Get all articles
      tags:
      - Articles
  /articles/:id:
    delete:
      consumes:
      - application/json
      description: Delete one article with provided ID
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Article deleted successfully
          schema:
            type: string
        "401":
          description: Unauthorized
          schema: {}
        "404":
          description: Article not found
          schema:
            type: string
        "500":
          description: You unable to delete this article!
          schema:
            type: string
      summary: Delete one article with provided ID from database
      tags:
      - Articles
    get:
      consumes:
      - application/json
      description: Get one article with provided ID
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Articles'
        "401":
          description: Unauthorized
          schema: {}
        "404":
          description: Article not found
          schema:
            type: string
      summary: Get one article with provided ID
      tags:
      - Articles
    put:
      consumes:
      - application/json
      description: Update information about an article
      parameters:
      - description: Body information for article update
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/articles.ArticleBody'
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Articles'
        "401":
          description: Unauthorized
          schema: {}
        "404":
          description: Article not found
          schema:
            type: string
      summary: Update information about an article
      tags:
      - Articles
  /articles/create:
    post:
      consumes:
      - application/json
      description: Creating a new article
      parameters:
      - description: Body information for article creation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/articles.ArticleBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Articles'
        "401":
          description: Unauthorized
          schema: {}
        "404":
          description: Article not found
          schema:
            type: string
      summary: Creating a new article
      tags:
      - Articles
  /comments:
    get:
      description: Returns all comments from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  items:
                    $ref: '#/definitions/models.Comments'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Returns all comments from database
      tags:
      - Comments
  /comments/:id:
    delete:
      description: Deletes user's comment from database(change flag isRemoved to 1)
      parameters:
      - description: Comment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  $ref: '#/definitions/models.Comments'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  type: object
              type: object
        "403":
          description: Forbidden
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  type: object
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  type: object
              type: object
      summary: Deletes user's comment from database
      tags:
      - Comments
  /comments/create:
    post:
      consumes:
      - application/json
      description: Creates a new comment in database, user id provided from JWT token
      parameters:
      - description: Body information for new comment
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/comments.CommentInput'
      - description: article ID for comment creation
        in: query
        name: article_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  $ref: '#/definitions/models.Comments'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Creates a new comment in database
      tags:
      - Comments
  /users:
    get:
      description: Get all active users in the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "401":
          description: Unauthorized
          schema: {}
      summary: Get all users in the database
      tags:
      - Users
  /users/:id:
    delete:
      description: Deletes user from database(change flag isRemoved to 1)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  type: object
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  type: object
              type: object
      summary: Deletes user from database
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Returns one user from database
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              allOf:
              - $ref: '#/definitions/models.User'
              - properties:
                  Data:
                    $ref: '#/definitions/models.User'
                type: object
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Returns one user from database
      tags:
      - Users
  /users/all:
    get:
      description: Get all users in the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "401":
          description: Unauthorized
          schema: {}
      summary: Get all users in the database
      tags:
      - Users
  /users/create:
    post:
      description: Allows to create a new user in database for existing user
      parameters:
      - description: Body information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.NewUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data: {}
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data: {}
              type: object
      summary: Allows loggined user to create a new user
      tags:
      - Users
  /users/login:
    post:
      consumes:
      - application/json
      description: Allows user to login in the system
      parameters:
      - description: Body information for login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HttpResponse'
      summary: Allows user to login in the system
      tags:
      - Users
  /users/register:
    post:
      consumes:
      - application/json
      description: Allows you to create a new user
      parameters:
      - description: Body information to create a new user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.NewUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.NewUser'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Allows you to create a new user
      tags:
      - Users
  /users/restore/:id:
    get:
      description: Restores user in database(change flag isRemoved to 0)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  type: object
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/models.HttpResponse'
            - properties:
                Data:
                  type: object
              type: object
      summary: Restores user in database
      tags:
      - Users
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
